version: '3.8'
services:
  server:
    image: customizedimg/httpd-server:v1
    ports:
      - '8080:80'

  nginx-proxy:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    command: certbot --nginx -d tst.dev.debuide.com --register-unsafely-without-email --test-cert  
    volumes:
      - ./deploy/default.conf:/etc/nginx/sites-available/default
    depends_on:
      - server
