version: '3.8'
services:
  server:
    image: customizedimg/httpd-server:v1
    ports:
      - '8080:80'

  nginx-proxy:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend/build:/var/www/html
      - ./deploy/default.conf:/etc/nginx/sites-available/default
    depends_on:
      - server
